/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as ANSRegistryContractJson } from "../ANSRegistry.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace ANSRegistryTypes {
  export type Fields = {
    admin: Address;
    recordTemplateId: HexString;
  };

  export type State = ContractState<Fields>;
}

class Factory extends ContractFactory<
  ANSRegistryInstance,
  ANSRegistryTypes.Fields
> {
  consts = {
    ErrorCodes: {
      InvalidCaller: BigInt(0),
      InvalidArgs: BigInt(1),
      ExpectAssetAddress: BigInt(2),
      NameHasBeenRegistered: BigInt(3),
      ContractNotExists: BigInt(4),
    },
  };

  at(address: string): ANSRegistryInstance {
    return new ANSRegistryInstance(address);
  }

  tests = {
    updateAdmin: async (
      params: TestContractParams<ANSRegistryTypes.Fields, { newAdmin: Address }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "updateAdmin", params);
    },
    newNode: async (
      params: TestContractParams<
        ANSRegistryTypes.Fields,
        { node: HexString; ownerContractId: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "newNode", params);
    },
    newSubNodeRecord: async (
      params: TestContractParams<
        ANSRegistryTypes.Fields,
        {
          node: HexString;
          label: HexString;
          owner: Address;
          ttl: bigint;
          resolver: HexString;
          payer: Address;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "newSubNodeRecord", params);
    },
  };
}

// Use this object to test and deploy the contract
export const ANSRegistry = new Factory(
  Contract.fromJson(
    ANSRegistryContractJson,
    "",
    "125ae52bad2a8ead1fa3ac791690114e7562404daa592c08546a1257c6a6176e"
  )
);

// Use this class to interact with the blockchain
export class ANSRegistryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ANSRegistryTypes.State> {
    return fetchContractState(ANSRegistry, this);
  }
}
