/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as CredentialTokenContractJson } from "../CredentialToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace CredentialTokenTypes {
  export type Fields = {
    registrar: HexString;
    name: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  CredentialTokenInstance,
  CredentialTokenTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as CredentialTokenTypes.Fields;
  }

  consts = {
    ErrorCodes: {
      InvalidCaller: BigInt(0),
      InvalidArgs: BigInt(1),
      ExpectAssetAddress: BigInt(2),
      NameHasBeenRegistered: BigInt(3),
      ContractNotExists: BigInt(4),
      NameHasExpired: BigInt(5),
      InvalidCredentialToken: BigInt(6),
    },
  };

  at(address: string): CredentialTokenInstance {
    return new CredentialTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParams<CredentialTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<
        TestContractParams<CredentialTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<
        TestContractParams<CredentialTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParams<CredentialTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    destroy: async (
      params: TestContractParams<
        CredentialTokenTypes.Fields,
        { refundAddress: Address }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroy", params);
    },
  };
}

// Use this object to test and deploy the contract
export const CredentialToken = new Factory(
  Contract.fromJson(
    CredentialTokenContractJson,
    "",
    "a664b4bd3070d857687a38de41f41a4372307d5c98a98a787e2185689799bfdb"
  )
);

// Use this class to interact with the blockchain
export class CredentialTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<CredentialTokenTypes.State> {
    return fetchContractState(CredentialToken, this);
  }

  methods = {
    getSymbol: async (
      params?: CredentialTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<CredentialTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        CredentialToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: CredentialTokenTypes.CallMethodParams<"getName">
    ): Promise<CredentialTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        CredentialToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: CredentialTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<CredentialTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        CredentialToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: CredentialTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<CredentialTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        CredentialToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends CredentialTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<CredentialTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      CredentialToken,
      this,
      calls,
      getContractByCodeHash
    )) as CredentialTokenTypes.MultiCallResults<Calls>;
  }
}
