/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as PrimaryRecordContractJson } from "../registrars/PrimaryRecord.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace PrimaryRecordTypes {
  export type Fields = {
    owner: Address;
    resolver: HexString;
    refundAddress: Address;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getResolver: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getRefundAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  PrimaryRecordInstance,
  PrimaryRecordTypes.Fields
> {
  consts = {
    ErrorCodes: {
      InvalidCaller: BigInt(0),
      InvalidArgs: BigInt(1),
      ExpectAssetAddress: BigInt(2),
      NameHasBeenRegistered: BigInt(3),
      ContractNotExists: BigInt(4),
      PrimaryRecordNotExists: BigInt(5),
    },
  };

  at(address: string): PrimaryRecordInstance {
    return new PrimaryRecordInstance(address);
  }

  tests = {
    getOwner: async (
      params: Omit<
        TestContractParams<PrimaryRecordTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getOwner", params);
    },
    getResolver: async (
      params: Omit<
        TestContractParams<PrimaryRecordTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getResolver", params);
    },
    getRefundAddress: async (
      params: Omit<
        TestContractParams<PrimaryRecordTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getRefundAddress", params);
    },
    setOwner: async (
      params: TestContractParams<
        PrimaryRecordTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setOwner", params);
    },
    setResolver: async (
      params: TestContractParams<
        PrimaryRecordTypes.Fields,
        { newResolver: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setResolver", params);
    },
    destroy: async (
      params: TestContractParams<PrimaryRecordTypes.Fields, { node: HexString }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroy", params);
    },
  };
}

// Use this object to test and deploy the contract
export const PrimaryRecord = new Factory(
  Contract.fromJson(
    PrimaryRecordContractJson,
    "",
    "0d828dfda703f6817981883611662f282434010ff0218c7c4c30b9f8fd0c08f0"
  )
);

// Use this class to interact with the blockchain
export class PrimaryRecordInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PrimaryRecordTypes.State> {
    return fetchContractState(PrimaryRecord, this);
  }

  methods = {
    getOwner: async (
      params?: PrimaryRecordTypes.CallMethodParams<"getOwner">
    ): Promise<PrimaryRecordTypes.CallMethodResult<"getOwner">> => {
      return callMethod(
        PrimaryRecord,
        this,
        "getOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getResolver: async (
      params?: PrimaryRecordTypes.CallMethodParams<"getResolver">
    ): Promise<PrimaryRecordTypes.CallMethodResult<"getResolver">> => {
      return callMethod(
        PrimaryRecord,
        this,
        "getResolver",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRefundAddress: async (
      params?: PrimaryRecordTypes.CallMethodParams<"getRefundAddress">
    ): Promise<PrimaryRecordTypes.CallMethodResult<"getRefundAddress">> => {
      return callMethod(
        PrimaryRecord,
        this,
        "getRefundAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends PrimaryRecordTypes.MultiCallParams>(
    calls: Calls
  ): Promise<PrimaryRecordTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      PrimaryRecord,
      this,
      calls,
      getContractByCodeHash
    )) as PrimaryRecordTypes.MultiCallResults<Calls>;
  }
}
