/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as PrimaryRegistrarContractJson } from "../registrars/PrimaryRegistrar.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace PrimaryRegistrarTypes {
  export type Fields = {
    registrarOwner: Address;
    recordTemplateId: HexString;
    recordTokenTemplateId: HexString;
  };

  export type State = ContractState<Fields>;

  export type NameRegisteredEvent = ContractEvent<{
    name: HexString;
    owner: Address;
    ttl: bigint;
  }>;
  export type NameRenewEvent = ContractEvent<{ name: HexString; ttl: bigint }>;
}

class Factory extends ContractFactory<
  PrimaryRegistrarInstance,
  PrimaryRegistrarTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as PrimaryRegistrarTypes.Fields;
  }

  eventIndex = { NameRegistered: 0, NameRenew: 1 };
  consts = {
    MinRentDuration: BigInt(2592000000),
    ErrorCodes: {
      InvalidCaller: BigInt(0),
      InvalidArgs: BigInt(1),
      ExpectAssetAddress: BigInt(2),
      NameHasBeenRegistered: BigInt(3),
      ContractNotExists: BigInt(4),
      PrimaryRecordNotExists: BigInt(5),
      NameHasExpired: BigInt(6),
      InvalidCredentialTokenId: BigInt(7),
    },
  };

  at(address: string): PrimaryRegistrarInstance {
    return new PrimaryRegistrarInstance(address);
  }

  tests = {
    register: async (
      params: TestContractParams<
        PrimaryRegistrarTypes.Fields,
        {
          name: HexString;
          owner: Address;
          payer: Address;
          resolver: HexString;
          duration: bigint;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "register", params);
    },
    renew: async (
      params: TestContractParams<
        PrimaryRegistrarTypes.Fields,
        { name: HexString; payer: Address; duration: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "renew", params);
    },
    cost: async (
      params: TestContractParams<
        PrimaryRegistrarTypes.Fields,
        { duration: bigint }
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "cost", params);
    },
    createRecordToken: async (
      params: TestContractParams<
        PrimaryRegistrarTypes.Fields,
        { path: HexString; name: HexString; payer: Address }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "createRecordToken", params);
    },
    preRegister: async (
      params: TestContractParams<
        PrimaryRegistrarTypes.Fields,
        { node: HexString; currentTs: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "preRegister", params);
    },
    withdraw: async (
      params: TestContractParams<
        PrimaryRegistrarTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
    updateRegistrarOwner: async (
      params: TestContractParams<
        PrimaryRegistrarTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "updateRegistrarOwner", params);
    },
  };
}

// Use this object to test and deploy the contract
export const PrimaryRegistrar = new Factory(
  Contract.fromJson(
    PrimaryRegistrarContractJson,
    "",
    "8a549a925b9a0066b714f5f01f8a730a40af76a3bebfcffafae1eeb900f43eb2"
  )
);

// Use this class to interact with the blockchain
export class PrimaryRegistrarInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PrimaryRegistrarTypes.State> {
    return fetchContractState(PrimaryRegistrar, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeNameRegisteredEvent(
    options: EventSubscribeOptions<PrimaryRegistrarTypes.NameRegisteredEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PrimaryRegistrar.contract,
      this,
      options,
      "NameRegistered",
      fromCount
    );
  }

  subscribeNameRenewEvent(
    options: EventSubscribeOptions<PrimaryRegistrarTypes.NameRenewEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      PrimaryRegistrar.contract,
      this,
      options,
      "NameRenew",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | PrimaryRegistrarTypes.NameRegisteredEvent
      | PrimaryRegistrarTypes.NameRenewEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      PrimaryRegistrar.contract,
      this,
      options,
      fromCount
    );
  }
}
