/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as PrimaryRecordOwnerContractJson } from "../test/PrimaryRecordOwner.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace PrimaryRecordOwnerTypes {
  export type Fields = {
    record: HexString;
  };

  export type State = ContractState<Fields>;
}

class Factory extends ContractFactory<
  PrimaryRecordOwnerInstance,
  PrimaryRecordOwnerTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as PrimaryRecordOwnerTypes.Fields;
  }

  at(address: string): PrimaryRecordOwnerInstance {
    return new PrimaryRecordOwnerInstance(address);
  }

  tests = {
    destroyRecord: async (
      params: TestContractParams<
        PrimaryRecordOwnerTypes.Fields,
        { node: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroyRecord", params);
    },
  };
}

// Use this object to test and deploy the contract
export const PrimaryRecordOwner = new Factory(
  Contract.fromJson(
    PrimaryRecordOwnerContractJson,
    "",
    "a8586228adfc687c34c9f4b7d423b113196e29a0b6212b088d8c0b63e0c11f91"
  )
);

// Use this class to interact with the blockchain
export class PrimaryRecordOwnerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<PrimaryRecordOwnerTypes.State> {
    return fetchContractState(PrimaryRecordOwner, this);
  }
}
