/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as RecordContractJson } from "../record.ral.json";

// Custom types for the contract
export namespace RecordTypes {
  export type Fields = {
    registrar: HexString;
    owner: HexString;
    ttl: bigint;
    resolver: HexString;
    refundAddress: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getRegistrar: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getTTL: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getResolver: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getRefundAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<RecordInstance, RecordTypes.Fields> {
  at(address: string): RecordInstance {
    return new RecordInstance(address);
  }

  tests = {
    getRegistrar: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getRegistrar", params);
    },
    getOwner: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getOwner", params);
    },
    setOwner: async (
      params: TestContractParams<RecordTypes.Fields, { newOwner: HexString }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setOwner", params);
    },
    getTTL: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTTL", params);
    },
    setTTL: async (
      params: TestContractParams<RecordTypes.Fields, { newTTL: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setTTL", params);
    },
    getResolver: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getResolver", params);
    },
    setResolver: async (
      params: TestContractParams<RecordTypes.Fields, { newResolver: HexString }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setResolver", params);
    },
    getRefundAddress: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getRefundAddress", params);
    },
    destroy: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroy", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Record = new Factory(
  Contract.fromJson(
    RecordContractJson,
    "",
    "db1b74b79b7a21500c4ae9b072987b594192e2e751fb8160f24800824f71663d"
  )
);

// Use this class to interact with the blockchain
export class RecordInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<RecordTypes.State> {
    return fetchContractState(Record, this);
  }

  methods = {
    getRegistrar: async (
      params?: RecordTypes.CallMethodParams<"getRegistrar">
    ): Promise<RecordTypes.CallMethodResult<"getRegistrar">> => {
      return callMethod(
        Record,
        this,
        "getRegistrar",
        params === undefined ? {} : params
      );
    },
    getOwner: async (
      params?: RecordTypes.CallMethodParams<"getOwner">
    ): Promise<RecordTypes.CallMethodResult<"getOwner">> => {
      return callMethod(
        Record,
        this,
        "getOwner",
        params === undefined ? {} : params
      );
    },
    getTTL: async (
      params?: RecordTypes.CallMethodParams<"getTTL">
    ): Promise<RecordTypes.CallMethodResult<"getTTL">> => {
      return callMethod(
        Record,
        this,
        "getTTL",
        params === undefined ? {} : params
      );
    },
    getResolver: async (
      params?: RecordTypes.CallMethodParams<"getResolver">
    ): Promise<RecordTypes.CallMethodResult<"getResolver">> => {
      return callMethod(
        Record,
        this,
        "getResolver",
        params === undefined ? {} : params
      );
    },
    getRefundAddress: async (
      params?: RecordTypes.CallMethodParams<"getRefundAddress">
    ): Promise<RecordTypes.CallMethodResult<"getRefundAddress">> => {
      return callMethod(
        Record,
        this,
        "getRefundAddress",
        params === undefined ? {} : params
      );
    },
  };

  async multicall<Calls extends RecordTypes.MultiCallParams>(
    calls: Calls
  ): Promise<RecordTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Record,
      this,
      calls
    )) as RecordTypes.MultiCallResults<Calls>;
  }
}
