/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as RecordTestContractJson } from "../test/RecordTest.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace RecordTestTypes {
  export type Fields = {
    record: HexString;
  };

  export type State = ContractState<Fields>;
}

class Factory extends ContractFactory<
  RecordTestInstance,
  RecordTestTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as RecordTestTypes.Fields;
  }

  at(address: string): RecordTestInstance {
    return new RecordTestInstance(address);
  }

  tests = {
    destroyRecord: async (
      params: Omit<
        TestContractParams<RecordTestTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroyRecord", params);
    },
  };
}

// Use this object to test and deploy the contract
export const RecordTest = new Factory(
  Contract.fromJson(
    RecordTestContractJson,
    "",
    "765329ee59e40f9d7108081a0fd0d70e5b44f2bd8eddedee1c4539bd479f36a3"
  )
);

// Use this class to interact with the blockchain
export class RecordTestInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<RecordTestTypes.State> {
    return fetchContractState(RecordTest, this);
  }
}
