/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as RecordContractJson } from "../Record.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace RecordTypes {
  export type Fields = {
    registrar: HexString;
    owner: Address;
    ttl: bigint;
    resolver: HexString;
    refundAddress: Address;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getRegistrar: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getTTL: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getRefundAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<RecordInstance, RecordTypes.Fields> {
  consts = {
    ErrorCodes: {
      InvalidCaller: BigInt(0),
      InvalidArgs: BigInt(1),
      ExpectAssetAddress: BigInt(2),
      NameHasBeenRegistered: BigInt(3),
      ContractNotExists: BigInt(4),
    },
  };

  at(address: string): RecordInstance {
    return new RecordInstance(address);
  }

  tests = {
    getRegistrar: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getRegistrar", params);
    },
    getOwner: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getOwner", params);
    },
    setOwner: async (
      params: TestContractParams<RecordTypes.Fields, { newOwner: Address }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setOwner", params);
    },
    getTTL: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTTL", params);
    },
    setTTL: async (
      params: TestContractParams<RecordTypes.Fields, { newTTL: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setTTL", params);
    },
    setResolver: async (
      params: TestContractParams<RecordTypes.Fields, { newResolver: HexString }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setResolver", params);
    },
    getRefundAddress: async (
      params: Omit<TestContractParams<RecordTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<Address>> => {
      return testMethod(this, "getRefundAddress", params);
    },
    destroy: async (
      params: TestContractParams<RecordTypes.Fields, { node: HexString }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroy", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Record = new Factory(
  Contract.fromJson(
    RecordContractJson,
    "",
    "0e308c0b0cbac94ed57fbf2523825d4fca4a1977554be4e63ec952df221942a7"
  )
);

// Use this class to interact with the blockchain
export class RecordInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<RecordTypes.State> {
    return fetchContractState(Record, this);
  }

  methods = {
    getRegistrar: async (
      params?: RecordTypes.CallMethodParams<"getRegistrar">
    ): Promise<RecordTypes.CallMethodResult<"getRegistrar">> => {
      return callMethod(
        Record,
        this,
        "getRegistrar",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getOwner: async (
      params?: RecordTypes.CallMethodParams<"getOwner">
    ): Promise<RecordTypes.CallMethodResult<"getOwner">> => {
      return callMethod(
        Record,
        this,
        "getOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTTL: async (
      params?: RecordTypes.CallMethodParams<"getTTL">
    ): Promise<RecordTypes.CallMethodResult<"getTTL">> => {
      return callMethod(
        Record,
        this,
        "getTTL",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRefundAddress: async (
      params?: RecordTypes.CallMethodParams<"getRefundAddress">
    ): Promise<RecordTypes.CallMethodResult<"getRefundAddress">> => {
      return callMethod(
        Record,
        this,
        "getRefundAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends RecordTypes.MultiCallParams>(
    calls: Calls
  ): Promise<RecordTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Record,
      this,
      calls,
      getContractByCodeHash
    )) as RecordTypes.MultiCallResults<Calls>;
  }
}
