/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as RegistrarContractJson } from "../registrar.ral.json";

// Custom types for the contract
export namespace RegistrarTypes {
  export type Fields = {
    registrarOwner: HexString;
    ansRegistryId: HexString;
    defaultResolverId: HexString;
  };

  export type State = ContractState<Fields>;

  export type NewNodeEvent = ContractEvent<{
    node: HexString;
    owner: HexString;
  }>;
  export type TransferEvent = ContractEvent<{
    node: HexString;
    oldOwner: HexString;
    newOwner: HexString;
  }>;
  export type NewTTLEvent = ContractEvent<{
    node: HexString;
    owner: HexString;
    ttl: bigint;
  }>;
  export type NewResolverEvent = ContractEvent<{
    node: HexString;
    owner: HexString;
    resolverId: HexString;
  }>;
}

class Factory extends ContractFactory<
  RegistrarInstance,
  RegistrarTypes.Fields
> {
  at(address: string): RegistrarInstance {
    return new RegistrarInstance(address);
  }

  tests = {
    rentPrice: async (
      params: TestContractParams<RegistrarTypes.Fields, { duration: bigint }>
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "rentPrice", params);
    },
    register: async (
      params: TestContractParams<
        RegistrarTypes.Fields,
        {
          name: HexString;
          owner: HexString;
          duration: bigint;
          payer: HexString;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "register", params);
    },
    registerWithResolver: async (
      params: TestContractParams<
        RegistrarTypes.Fields,
        {
          name: HexString;
          owner: HexString;
          duration: bigint;
          payer: HexString;
          resolverId: HexString;
        }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "registerWithResolver", params);
    },
    removeRecord: async (
      params: TestContractParams<
        RegistrarTypes.Fields,
        { node: HexString; record: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "removeRecord", params);
    },
    unregister: async (
      params: TestContractParams<RegistrarTypes.Fields, { node: HexString }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "unregister", params);
    },
    renew: async (
      params: TestContractParams<
        RegistrarTypes.Fields,
        { node: HexString; duration: bigint; payer: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "renew", params);
    },
    setOwner: async (
      params: TestContractParams<
        RegistrarTypes.Fields,
        { node: HexString; newOwner: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setOwner", params);
    },
    setResolver: async (
      params: TestContractParams<
        RegistrarTypes.Fields,
        { node: HexString; resolverId: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setResolver", params);
    },
    withdraw: async (
      params: TestContractParams<
        RegistrarTypes.Fields,
        { to: HexString; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Registrar = new Factory(
  Contract.fromJson(
    RegistrarContractJson,
    "",
    "21aa86842370520a75317b6582133bd4ee06c0e02cc328be01b7e541ac9a89e1"
  )
);

// Use this class to interact with the blockchain
export class RegistrarInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<RegistrarTypes.State> {
    return fetchContractState(Registrar, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeNewNodeEvent(
    options: SubscribeOptions<RegistrarTypes.NewNodeEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Registrar.contract,
      this,
      options,
      "NewNode",
      fromCount
    );
  }

  subscribeTransferEvent(
    options: SubscribeOptions<RegistrarTypes.TransferEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Registrar.contract,
      this,
      options,
      "Transfer",
      fromCount
    );
  }

  subscribeNewTTLEvent(
    options: SubscribeOptions<RegistrarTypes.NewTTLEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Registrar.contract,
      this,
      options,
      "NewTTL",
      fromCount
    );
  }

  subscribeNewResolverEvent(
    options: SubscribeOptions<RegistrarTypes.NewResolverEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Registrar.contract,
      this,
      options,
      "NewResolver",
      fromCount
    );
  }

  subscribeAllEvents(
    options: SubscribeOptions<
      | RegistrarTypes.NewNodeEvent
      | RegistrarTypes.TransferEvent
      | RegistrarTypes.NewTTLEvent
      | RegistrarTypes.NewResolverEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      Registrar.contract,
      this,
      options,
      fromCount
    );
  }
}
