/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as RegisterScriptJson } from "../scripts/Register.ral.json";

export const Register = new ExecutableScript<{
  registrar: HexString;
  name: HexString;
  resolver: HexString;
}>(Script.fromJson(RegisterScriptJson));
