/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as SecondaryRegistrarContractJson } from "../registrars/SecondaryRegistrar.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace SecondaryRegistrarTypes {
  export type Fields = {
    primaryRegistrar: HexString;
    recordTemplateId: HexString;
  };

  export type State = ContractState<Fields>;

  export type NameRegisteredEvent = ContractEvent<{
    name: HexString;
    owner: Address;
  }>;
}

class Factory extends ContractFactory<
  SecondaryRegistrarInstance,
  SecondaryRegistrarTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as SecondaryRegistrarTypes.Fields;
  }

  eventIndex = { NameRegistered: 0 };
  consts = {
    ErrorCodes: {
      InvalidCaller: BigInt(0),
      InvalidArgs: BigInt(1),
      ExpectAssetAddress: BigInt(2),
      NameHasBeenRegistered: BigInt(3),
      ContractNotExists: BigInt(4),
      PrimaryRecordNotExists: BigInt(5),
    },
  };

  at(address: string): SecondaryRegistrarInstance {
    return new SecondaryRegistrarInstance(address);
  }

  tests = {
    register: async (
      params: TestContractParams<
        SecondaryRegistrarTypes.Fields,
        { name: HexString; owner: Address; payer: Address; resolver: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "register", params);
    },
  };
}

// Use this object to test and deploy the contract
export const SecondaryRegistrar = new Factory(
  Contract.fromJson(
    SecondaryRegistrarContractJson,
    "",
    "a6064c2207259176d88d050f3d27529ca2d0ed0bc7e4eb90af29441d03c1c871"
  )
);

// Use this class to interact with the blockchain
export class SecondaryRegistrarInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SecondaryRegistrarTypes.State> {
    return fetchContractState(SecondaryRegistrar, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeNameRegisteredEvent(
    options: EventSubscribeOptions<SecondaryRegistrarTypes.NameRegisteredEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SecondaryRegistrar.contract,
      this,
      options,
      "NameRegistered",
      fromCount
    );
  }
}
