/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as SecondaryRecordOwnerContractJson } from "../test/SecondaryRecordOwner.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace SecondaryRecordOwnerTypes {
  export type Fields = {
    record: HexString;
  };

  export type State = ContractState<Fields>;
}

class Factory extends ContractFactory<
  SecondaryRecordOwnerInstance,
  SecondaryRecordOwnerTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as SecondaryRecordOwnerTypes.Fields;
  }

  at(address: string): SecondaryRecordOwnerInstance {
    return new SecondaryRecordOwnerInstance(address);
  }

  tests = {
    destroyRecord: async (
      params: TestContractParams<
        SecondaryRecordOwnerTypes.Fields,
        { node: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroyRecord", params);
    },
  };
}

// Use this object to test and deploy the contract
export const SecondaryRecordOwner = new Factory(
  Contract.fromJson(
    SecondaryRecordOwnerContractJson,
    "",
    "fc58df069b4a1490e256beae9da64a9d7fdf32b31f1c3ceecfe2953cc6f6ce27"
  )
);

// Use this class to interact with the blockchain
export class SecondaryRecordOwnerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SecondaryRecordOwnerTypes.State> {
    return fetchContractState(SecondaryRecordOwner, this);
  }
}
